"""String-aware comment lexer for the consolidation runner.

One scan of a source file gives two products:

* comments, each with its exact character span, so a unit is never invented
  inside a string literal, a regex literal or a heredoc;
* code tokens: the file with every comment removed, normalized, so that two
  revisions can be compared token for token (`code-invariance-check`).

Python is lexed by the stdlib `tokenize`; every other language by a small state
machine. A lexer in CERTAIN handles every literal form that can hide a comment
marker; for any other lexer the invariance check reports "cannot prove" and the
test suite decides.

Directives (comments a tool reads, such as `eslint-disable` or `# noqa`) and
license headers are never units: deleting one changes a build, a lint or a legal
notice without changing one code token, so no token comparison can see the loss.
"""
import ast
import bisect
import io
import re
import tokenize
from pathlib import PurePosixPath


class UnsupportedLanguage(Exception):
    pass


# ------------------------------------------------------------------ directives
TOOL_DIRECTIVES = (
    r"^eslint(-disable|-enable|-env)?(\s|$|-)", r"^globals?\s+[A-Za-z_$]\w*(\s*,\s*[A-Za-z_$]\w*)*\s*:", r"^@ts-(ignore|expect-error|nocheck|check)\b",
    r"^prettier-ignore\b", r"^(istanbul|c8|v8)\s+ignore\b", r"^js[hl]int\b", r"^@flow\b",
    r"^@jsx(ImportSource|Frag|Runtime)?\b", r"\bwebpack[A-Z]\w*\s*:", r"@vite-ignore\b",
    r"^#(end)?region\b", r"(?i)(^|#)\s*noqa\b", r"^type:\s*ignore\b", r"^(pylint|pyright|mypy|isort|ruff)\s*:",
    r"\bpylint:\s*\w", r"^pyre-", r"^pytype:", r"^yapf:", r"^autopep8:", r"^lgtm\[", r"^codespell:",
    r"^fmt:\s*(on|off|skip)\b", r"^format:\s*(on|off)\b", r"\bpragma:\s*no\s*(cover|branch)\b", r"\bnosec\b", r"-\*-.*-\*-",
    r"^(vim?|ex):\s*(set\b|\w+=)", r"^go:\w", r"^\+build\b", r"\bnolint\b", r"\bNOLINT(BEGIN|END|NEXTLINE)?\b",
    r"^clang-format\s+(on|off)\b", r"^rubocop:", r"^frozen_string_literal:", r"^shellcheck\s",
    r"@formatter:(on|off)", r"^phpcs:", r"@(phpstan|psalm)-", r"@codeCoverageIgnore",
    r"(?i)resharper\s+(disable|restore)", r"^@?noinspection\b", r"^language=[\w-]+$", r"^\[if\s", r"\[endif\]",
    r"^/?line\s+\S+\:\d+",
    r"@cc_on", r"^[#@]\s*source(Mapping)?URL=", r"^@ngInject\b", r"^(stylelint|markdownlint)-(disable|enable)",
    r"^cspell:", r"^(syntax|escape|check)\s*=\s*\w+$", r"^@generated\b",
    r"^[#@]__(PURE|NOINLINE|NO_SIDE_EFFECTS)__\??$",
    # --- TypeScript / JavaScript tooling
    r"^\s*<(reference|amd-module|amd-dependency)\b", r"^tslint:", r"^biome-ignore\b", r"^oxlint-",
    r"^deno-lint-ignore\b", r"^\$FlowFixMe\b", r"^@noflow\b",
    r"^exported\s+[A-Za-z_$][\w$]*(\s*,\s*[A-Za-z_$][\w$]*)*\s*$", r"^@(jest|vitest)-environment\b",
    r"^@refresh\b",
    # --- Go
    r"^#\s*(include|cgo|define|undef|ifdef|ifndef|endif|pragma)\b", r"^/?export\b", r"^node:coverage\b",
    r"(?i)^notreached\b", r"(?i)^coverity[\[:,]",
    r"^lint:ignore\b", r"^Code generated\b.*DO NOT EDIT", r"^(Unordered output|Output):(\s|$)",
    r"^\$NON-NLS", r"^lang=\w", r"^htmlmin:ignore\b",
    # --- C / C++ tooling
    r"(?i)^fall\s*-?\s*through\b", r"(?i)^fallthru\b", r"\bLCOV_EXCL_", r"\bGCOVR_EXCL_",
    r"\bcppcheck-suppress\b", r"\bIWYU pragma\b", r"^lint\s*[-+!]+[\w{(]", r"\bNOSONAR\b", r"^<!\[CDATA\[", r"^\]\]>",
    # --- Java family
    r"CHECKSTYLE:(OFF|ON)", r"\bNOPMD\b", r"^spotless:", r"^swiftlint:", r"^ktlint\b[-:]",
    r"^scalastyle:", r"^scalafmt\b", r"^ignore_for_file:", r"^ignore:\s*[a-z_]+(\s*,\s*[a-z_]+)*\s*$",
    # --- .NET
    r"^<auto-generated\b",
    # --- PHP docblock tags a tool reads (Doctrine, PHPUnit)
    r"^@[A-Z]\w*\\", r"^@(dataProvider|depends|group|testWith|test)\b",
    r"@codingStandardsIgnore",
    # --- CSS
    r"^autoprefixer\s*:", r"\bpurgecss\b", r"^rtl:", r"@noflip\b",
    # --- shell and schedulers
    r"^SBATCH\b", r"^PBS\b", r"^\$\s*-", r"^compdef\b", r"^#+\s*BEGIN INIT INFO", r"^chkconfig:",
    r"^requires\s+-",
    # --- HTML templating
    r"^/?ko(\s|$)", r"^#include\b", r"^build:", r"^endbuild\b", r"^inject:", r"^svelte-ignore\b",
    # --- SQL migration tools
    r"^liquibase\b", r"^changeset\s+\S+:\S+", r"^\+goose\b", r"^\+migrate\b", r"^name:\s*\w+\s*:",
    r"^migrate:(up|down)", r"^![0-9]{4,8}\b",
    # --- Go code-generator markers (+kubebuilder:…, +k8s:…=…, +optional)
    r"^\+[A-Za-z][\w.\-]*([:=]|$)",
    # --- Fortran sentinels and Haskell pragmas
    r"(?i)^\$(omp|acc)\b", r"(?i)^(DIR|DEC|GCC|SUN|IBM|PGI)\$", r"^\$\s", r"(?i)^#\s*[A-Z_]+\b",
)

# Any line of a whole-line comment group matching one of these excludes the whole group.
LICENSE_MARKERS = (
    r"(?i)\bcopyright\b", r"©", r"\(\s*[cC]\s*\)\s*[*·:]?\s*\d{4}",
    r"\(\s*[cC]\s*\)\s+[A-Z][\w&.,'-]*(\s+[A-Z][\w&.,'-]*)*,?\s+\d{4}", r"SPDX-[A-Za-z-]+:",
    r"(?i)under the (MIT|Apache|BSD|ISC|L?GPL|AGPL|MPL|EPL|EUPL)\b[^\n]*licen[cs]e",
    r"(?i)\b(MIT|Apache|BSD|ISC|MPL|EPL|EUPL|Zlib|Boost Software)\b[\w\s,.\-]{0,25}\blicen[cs]e\b",
    r"(?i)@(license|preserve)\b",
    r"(?i)licensed under", r"(?i)permission is hereby granted", r"(?i)all rights reserved",
    r"(?i)GNU (Lesser |Affero )?General Public License", r"(?i)Mozilla Public License",
    r"(?i)WITHOUT ANY WARRANTY", r"(?i)Redistribution and use", r"(?i)THE SOFTWARE IS PROVIDED",
    r"(?i)free software", r"(?i)\"AS IS\"",
)


def directive_matcher(extra=()):
    """Return a function classifying a comment's inner text as "license", "tool" or None.
    Docblock bodies are matched per line, so a directive on the third ` * ` line is seen."""
    tool = [re.compile(p, re.M) for p in (*TOOL_DIRECTIVES, *extra)]
    lic = [re.compile(p, re.M) for p in LICENSE_MARKERS]

    def match(inner):
        body = inner.strip()
        body = re.sub(r"(?m)^[ \t]*\*+[ \t]?", "", body)   # docblock prefixes, per line
        body = body.lstrip("*!/ ").strip()                  # leftover marker halves
        flat = re.sub(r"\s+", " ", body)                    # licence text may wrap mid-phrase
        if any(p.search(flat) for p in lic):
            return "license"
        if any(p.search(body) for p in tool):
            return "tool"
        return None
    return match


# ------------------------------------------------------------------ language map
_EXT = {}


def _reg(lang, *exts):
    for e in exts:
        _EXT[e] = lang


_reg("python", ".py", ".pyw", ".pyi")
_reg("js", ".js", ".mjs", ".cjs", ".ts", ".mts", ".cts")
_reg("jsx", ".jsx", ".tsx")
_reg("c", ".c", ".h", ".cpp", ".cc", ".cxx", ".hpp", ".hxx", ".hh", ".ino")
_reg("java", ".java")
_reg("kotlin", ".kt", ".kts")
_reg("scala", ".scala")
_reg("swift", ".swift")
_reg("groovy", ".groovy", ".gradle")
_reg("dart", ".dart")
_reg("csharp", ".cs")
_reg("go", ".go")
_reg("rust", ".rs")
_reg("proto", ".proto", ".jsonc", ".json5")
_reg("css", ".css")
_reg("scss", ".scss", ".less")
_reg("sass", ".sass")
_reg("sql", ".sql")
_reg("php", ".php", ".phtml")
_reg("html", ".html", ".htm", ".vue", ".svelte", ".xhtml")
_reg("xml", ".xml", ".xsd", ".xsl", ".xslt", ".svg", ".csproj", ".vbproj", ".config", ".plist", ".xaml",
     ".resx", ".nuspec", ".props", ".targets", ".pubxml")
_reg("razor", ".cshtml", ".vbhtml", ".razor")
_reg("aspnet", ".aspx", ".ascx", ".master")
_reg("shell", ".sh", ".bash", ".zsh", ".ksh", ".fish")
_reg("powershell", ".ps1", ".psm1", ".psd1")
_reg("batch", ".bat", ".cmd")
_reg("vb", ".vb", ".vbs", ".bas", ".frm")
_reg("apex", ".cls")
_reg("fortran", ".f90", ".f95", ".f03", ".f08")
_reg("fortran-fixed", ".f", ".for", ".f77")
_reg("lua", ".lua")
_reg("haskell", ".hs", ".elm")
_reg("hash", ".rb", ".r", ".pl", ".pm", ".tcl", ".yaml", ".yml", ".toml", ".mk", ".cmake", ".ex",
     ".exs", ".graphql", ".gql", ".tf", ".hcl", ".nix")
_reg("hashline", ".dockerfile", ".gitignore", ".gitattributes", ".dockerignore", ".env")
_reg("ini", ".ini", ".cfg", ".conf", ".editorconfig")
_reg("properties", ".properties")
_reg("lisp", ".lisp", ".clj", ".cljs", ".cljc", ".el", ".scm", ".rkt", ".asm")
_reg("gas", ".s")
_reg("none", ".json", ".txt", ".csv", ".lock", ".map")

_NAMES = {"makefile": "hash", "gnumakefile": "hash", "jenkinsfile": "groovy", "vagrantfile": "hash",
          "rakefile": "hash", "gemfile": "hash", "cmakelists.txt": "hash", "procfile": "hashline",
          ".gitignore": "hashline", ".dockerignore": "hashline", ".gitattributes": "hashline",
          ".env": "hashline", ".editorconfig": "ini"}


def language_for(path):
    p = PurePosixPath(str(path).replace("\\", "/"))
    name = p.name.lower()
    if name in _NAMES:
        return _NAMES[name]
    if name.startswith(("dockerfile", "containerfile")):
        return "hashline"
    return _EXT.get(p.suffix.lower())


# ------------------------------------------------------------------ scanners
class Scan:
    def __init__(self):
        self.comments = []   # (start, end, inner_text); end exclusive, never past the line end
        self.tokens = []
        self.uncertain = False   # a construct this scanner cannot decide; the suite decides
        self.doc = False         # a runtime-read doc comment exists (C4)

    def tok(self, t):
        self.tokens.append(t)


_IDENT = re.compile(r"[A-Za-z_$À-￿][\w$À-￿]*")
_NUMBER = re.compile(r"\d[\w.]*")
_CHAR_LIT = re.compile(r"'(?:\\.[^'\n]{0,9}|[^'\\\n])'")
_REGEX_PREV = set("(,=:[!&|?{};+-*%<>~^}") | {"return", "typeof", "case", "do", "else", "in", "of", "new",
                                            "delete", "void", "throw", "yield", "await", "instanceof", None}

_CLIKE = {
    "js": dict(line=("//",), block=("/*", "*/"), quotes={'"': "bs", "'": "bs"}, template=True, regex=True,
               nl_extra=("\u2028", "\u2029")),
    "jsx": dict(line=("//",), block=("/*", "*/"), quotes={'"': "bs", "'": "bs"}, template=True, regex=True,
                jsx=True, nl_extra=("\u2028", "\u2029")),
    "c": dict(line=("//",), block=("/*", "*/"), quotes={'"': "bs"}, chars=True, cpp_raw=True, splice=True),
    "java": dict(line=("//",), block=("/*", "*/"), quotes={'"': "bs"}, chars=True, triple=True),
    "csharp": dict(line=("//",), block=("/*", "*/"), quotes={'"': "bs"}, chars=True, verbatim=True,
                   triple=True, interp=True, nl_extra=("\u0085",), doc=("///", "/**")),
    "kotlin": dict(line=("//",), block=("/*", "*/"), quotes={'"': "bs", "'": "bs"}, triple=True,
                   nested=True, dollar_hole=True),
    "scala": dict(line=("//",), block=("/*", "*/"), quotes={'"': "bs", "'": "bs"}, triple=True, nested=True),
    "swift": dict(line=("//",), block=("/*", "*/"), quotes={'"': "bs", "'": "bs"}, triple=True,
                  nested=True, paren_interp=True),
    "groovy": dict(line=("//",), block=("/*", "*/"), quotes={'"': "bs", "'": "bs"}, triple=True),
    "dart": dict(line=("//",), block=("/*", "*/"), quotes={'"': "bs", "'": "bs"}, triple=True),
    "apex": dict(line=("//",), block=("/*", "*/"), quotes={'"': "bs", "'": "bs"}),
    "go": dict(line=("//",), block=("/*", "*/"), quotes={'"': "bs"}, chars=True, raw_backtick=True),
    "rust": dict(line=("//",), block=("/*", "*/"), quotes={'"': "bs"}, chars=True, nested=True, rust_raw=True, doc=("///", "//!", "/**", "/*!")),
    "proto": dict(line=("//",), block=("/*", "*/"), quotes={'"': "bs", "'": "bs"}),
    "css": dict(line=(), block=("/*", "*/"), quotes={'"': "bs", "'": "bs"}),
    "scss": dict(line=("//",), block=("/*", "*/"), quotes={'"': "bs", "'": "bs"}, css_url=True),
    "sass": dict(line=("//",), block=("/*", "*/"), quotes={'"': "bs", "'": "bs"}, css_url=True),
    "sql": dict(line=("--",), block=("/*", "*/"), quotes={"'": "double", '"': "double"}, brackets=True,
                dollar=True, nested=True, dashdash_space=True, bs_uncertain=True),
    "php": dict(line=("//", "#"), block=("/*", "*/"), quotes={'"': "bs", "'": "bs"}, php=True,
                multiline_strings=True, heredoc=True, doc=("/**",)),
    "powershell": dict(line=("#",), block=("<#", "#>"), quotes={"'": "double", '"': "backtick"},
                       herestring=True, hash_needs_space=True, multiline_strings=True),
    "vb": dict(line=("'",), block=None, quotes={'"': "double"}, rem=True),
    "fortran": dict(line=("!",), block=None, quotes={'"': "double", "'": "double"}),
    "lua": dict(line=("--",), block=("--[[", "]]"), quotes={'"': "bs", "'": "bs"}, lua_long=True),
    "haskell": dict(line=("--",), block=("{-", "-}"), quotes={'"': "bs"}, chars=True, nested=True,
                    opdash=True, bs_esc=True),
    "lisp": dict(line=(";",), block=None, quotes={'"': "bs"}, multiline_strings=True, bs_esc=True),
    "gas": dict(line=("#",), block=None, quotes={'"': "bs", "'": "bs"}),
    "plain": dict(line=(), block=None, quotes={}),
}

# CERTAIN holds only the languages whose fixes are tested here (owner decision, "narrow +
# strengthen"): Python, JS/TS, C#, Java, C/C++, SQL, PHP, CSS. Every other language reports
# "cannot prove" and its unit runs the test suite.
CERTAIN = {"python", "js", "c", "java", "csharp", "css", "sql", "php"}


def _string_end(text, i, n, q, esc, multiline):
    """Offset past the closing quote, and whether the quote closed: a string that reaches `n`
    without its terminator is unterminated, and its caller stops being certain (B10)."""
    j = i + 1
    while j < n:
        ch = text[j]
        if esc == "bs" and ch == "\\":
            # an escaped CRLF is one line continuation: skip both halves, keep the string open,
            # so the text after it is never mistaken for code (B4)
            if text[j + 1:j + 3] == "\r\n":
                j += 3
            else:
                j += 2
            continue
        if esc == "backtick" and ch == "`":
            j += 2
            continue
        if ch == q:
            if esc == "double" and j + 1 < n and text[j + 1] == q:
                j += 2
                continue
            return j + 1, True
        if ch == "\n" and esc == "bs" and not multiline:
            return j, False   # unterminated single-line string ends at the line end
        j += 1
    return n, False


_HOLE_CURLY = re.compile(r"\$\{|\{")
_HOLE_PAREN = re.compile(r"\\\(")
_JSX_PREV = _REGEX_PREV | {")", "]"}


def _scan_interp(text, i, n, cfg, scan, q, kind, verbatim=False):
    """Scan an interpolated string from its opening quote at i — never from a prefix. kind
    'interp': {…} holes with {{ literals (C# $"; with `verbatim`, C# $@": "" is the quote, \\ is
    literal, newlines are text); Swift \\( uses 'paren'; 'dollar': ${…} holes and bare $ident
    (Kotlin). Hole bodies are scanned as code, so a comment marker inside a hole's nested quotes
    is never a comment (B7). Returns (offset, closed): a scan that reaches `n` without its
    closing quote is unterminated, and a verbatim caller stops being certain (B10)."""
    hole = _HOLE_PAREN if kind == "paren" else _HOLE_CURLY
    seg = i
    j = i + 1
    closed = False
    while j < n:
        ch = text[j]
        if kind == "interp" and text.startswith(("{{", "}}"), j):
            j += 2
            continue
        if verbatim and text.startswith(q * 2, j):
            j += 2
            continue
        if kind == "paren" and ch == "\\" and text[j + 1:j + 2] != "(":
            j += 2
            continue
        if kind in ("interp", "dollar") and ch == "\\" and not verbatim:
            j += 2
            continue
        if kind == "dollar" and ch == "$":
            m = _IDENT.match(text, j + 1)
            if m:
                scan.tok(text[seg:j + 1])
                _scan_clike(text, cfg, scan, j + 1, j + 1 + len(m.group(0)))
                seg = j + 1 + len(m.group(0))
                j = seg
                continue
        m = hole.match(text, j)
        if m:
            scan.tok(text[seg:j])
            scan.tok(m.group(0))
            k = _scan_clike(text, cfg, scan, m.end(), n, brace_stop=(kind != "paren"),
                            paren_stop=(kind == "paren"))
            scan.tok(text[k:k + 1])
            seg = k + 1
            j = k + 1
            continue
        if ch == q:
            j += 1
            closed = True
            break
        if ch == "\n" and not verbatim:
            break
        j += 1
    scan.tok(text[seg:min(j, n)])
    return min(j, n), closed


_CS_INTERP = re.compile(r'(\$+@?|@\$+)("+)')


def _tag_end(text, i, n):
    """Offset just past the '>' of the tag at i, quotes honoured."""
    q = None
    k = i
    while k < n:
        ch = text[k]
        if q:
            if ch == q:
                q = None
        elif ch in "\"'":
            q = ch
        elif ch == ">":
            return k + 1
        k += 1
    return n


def _scan_jsx_children(text, cfg, scan, i, n):
    """Scan JSX children from i: text runs (never comments — `//` and `/*` are text here),
    `{expr}` holes and nested elements, until the matching close tag or end. Returns the offset
    of the '<' that closes this level (B9)."""
    sep = False

    def chunk(t):
        nonlocal sep
        if sep and scan.tokens:
            scan.tok(" ")
        scan.tok(t)
        sep = False

    while i < n:
        c = text[i]
        if c == "{":
            scan.tok("{")
            k = _scan_clike(text, cfg, scan, i + 1, n, brace_stop=True)
            scan.tok("}")
            i = k + 1
            continue
        if text.startswith("</", i) or re.match(r"<[A-Za-z]", text[i:i + 2]):
            if text.startswith("</", i):
                return i
            j = _tag_end(text, i, n)
            scan.tok(text[i:j])
            if not text[i:j].endswith("/>"):
                k = _scan_jsx_children(text, cfg, scan, j, n)
                j2 = _tag_end(text, k, n)
                scan.tok(text[k:j2])
                i = j2
            else:
                i = j
            continue
        j = i
        while j < n and text[j] not in "<{":
            j += 1
        for m in re.finditer(r"\S+|\s+", text[i:j]):
            if m.group(0)[0].isspace():
                sep = True
            else:
                chunk(m.group(0))
        i = j
    return i


def _scan_clike(text, cfg, scan, pos=0, end=None, brace_stop=False, stop=None, paren_stop=False):
    """Scan text[pos:end] into `scan`. Returns the offset where scanning stopped.

    A single " " token separates two code tokens whenever whitespace or a comment ran between
    them (B1), so `a .b` and `a.b` compare differently while a removed comment does not."""
    n = len(text) if end is None else end
    line_m = cfg.get("line", ())
    block = cfg.get("block")
    quotes = cfg.get("quotes", {})
    nl_extra = cfg.get("nl_extra", ())
    depth = 0
    prev = None
    i = pos
    sep = False

    def emit(t):
        nonlocal sep
        if sep and scan.tokens:
            scan.tok(" ")
        sep = False
        scan.tok(t)

    while i < n:
        c = text[i]
        if stop and text.startswith(stop, i):
            return i
        if brace_stop:
            if c == "{":
                depth += 1
            elif c == "}":
                if depth == 0:
                    return i
                depth -= 1
        if paren_stop:
            if c == "(":
                depth += 1
            elif c == ")":
                if depth == 0:
                    return i
                depth -= 1
        if block and text.startswith(block[0], i):
            j = i + len(block[0])
            lvl = 1
            closed = False
            while j < n and lvl:
                if cfg.get("nested") and text.startswith(block[0], j):
                    lvl += 1
                    j += len(block[0])
                elif text.startswith(block[1], j):
                    lvl -= 1
                    j += len(block[1])
                else:
                    j += 1
            closed = lvl == 0
            if closed:
                inner = text[i + len(block[0]):max(i + len(block[0]), j - len(block[1]))]
                if any(text.startswith(m, i) for m in cfg.get("doc", ())):
                    scan.doc = True
                    inner = "\x00doc\n" + inner   # a doc comment: a unit only under comment-fine (C4)
                scan.comments.append((i, j, inner))
                sep = True   # a comment separates what it stands between
            else:
                # unterminated: never a unit; the file is no longer certain (B10)
                scan.uncertain = True
                emit(text[i:j])
            i = j
            continue
        m = next((mk for mk in line_m if text.startswith(mk, i)), None)
        if m == "#" and cfg.get("php") and text.startswith("#[", i):
            m = None   # PHP 8 attribute
        if m and cfg.get("hash_needs_space") and i > 0 and text[i - 1] not in " \t\n;({":
            m = None
        if m == "--" and cfg.get("dashdash_space"):
            nxt = text[i + 2:i + 3]
            if nxt and nxt not in " \t\r\n\f\v":
                m = None   # `5--1` is arithmetic in this dialect; the file becomes uncertain
                scan.uncertain = True
        if m == "--" and cfg.get("opdash") and text[i + 2:i + 3] and text[i + 2] in "!#$%&*+./<=>?@\\^|~-":
            m = None   # Haskell `-->`, `<->`, `|--` are operators, not comments
        if (m is None and cfg.get("rem") and re.match(r"(?i)rem(\s|$)", text[i:i + 4])
                and text[text.rfind("\n", 0, i) + 1:i].strip() == ""):
            m = text[i:i + 3]
        if m:
            j = i
            while j < n and text[j] != "\n" and text[j] != "\r" and text[j] not in nl_extra:
                if stop and cfg.get("php") and text.startswith(stop, j):
                    break   # PHP: `?>` ends a single-line comment
                j += 1
            if cfg.get("splice"):
                # C/C++ phase-2 splice: a line comment whose line ends in an odd run of
                # backslashes continues onto the next line, and the unit covers it (B4)
                while j < n and text[j] in "\r\n":
                    k2, bs = j, 0
                    while k2 > i and text[k2 - 1] == "\\":
                        bs += 1
                        k2 -= 1
                    if bs % 2 != 1:
                        break
                    after = j + 2 if text[j:j + 2] == "\r\n" else j + 1
                    nxt = text.find("\n", after)
                    j = n if nxt < 0 else nxt
            k = j - 1 if j > i and j < n and text[j - 1] == "\r" else j
            k = min(k, n)
            inner = text[i + len(m):max(i + len(m), k)]
            if any(text.startswith(dm, i) for dm in cfg.get("doc", ())):
                scan.doc = True
                inner = "\x00doc\n" + inner
            scan.comments.append((i, max(i + len(m), k), inner))
            i = j
            continue
        if cfg.get("bs_esc") and c == "\\":
            emit(text[i:i + 2]); i += 2   # Lisp/Haskell: an escaped char is never a marker
            continue
        if cfg.get("lua_long"):
            mm = re.match(r"\[(=*)\[", text[i:i + 12])
            if mm:
                close = "]" + mm.group(1) + "]"
                k = text.find(close, i)
                if k < 0:
                    scan.uncertain = True   # a long bracket with no closer swallowed the rest (B10)
                    j = n
                else:
                    j = k + len(close)
                emit(text[i:j]); prev = "str"; i = j
                continue
        if cfg.get("heredoc") and text.startswith("<<<", i):
            mm = re.match(r"<<<\s*(['\"]?)(\w+)\1", text[i:])
            if mm:
                close = re.compile(r"\n\s*" + re.escape(mm.group(2)) + r"\b")
                cm = close.search(text, i + mm.end())
                if cm is None:
                    scan.uncertain = True   # a heredoc with no terminator swallowed the rest (B10)
                    j = n
                else:
                    j = cm.end()
                emit(text[i:j]); prev = "str"; i = j
                continue
        if cfg.get("triple") and (text.startswith('"""', i) or text.startswith("'''", i)):
            q = text[i:i + 3]
            k = text.find(q, i + 3)
            if k < 0:
                scan.uncertain = True   # a triple quote with no closer swallowed the rest (B10)
                j = n
            else:
                j = k + 3
            emit(text[i:j]); prev = "str"; i = j
            continue
        mm = _CS_INTERP.match(text, i) if cfg.get("interp") else None
        if mm:
            qpos, run = mm.start(2), len(mm.group(2))
            if "@" not in mm.group(1) and run >= 3:
                # raw interpolated ($"""…""", $$"""…"""): opaque up to the closing quote run;
                # its holes stay inside the token, so a change there fails closed
                j = text.find('"' * run, qpos + run)
                if j < 0:
                    scan.uncertain = True
                j = n if j < 0 else j + run
                emit(text[i:j]); prev = "str"; i = j
                continue
            emit(mm.group(1))   # the prefix; the scan starts at the quote (R-lexer 1)
            j, closed = _scan_interp(text, qpos, n, cfg, scan, '"', "interp", verbatim="@" in mm.group(1))
            if not closed and j >= n:
                scan.uncertain = True   # an unclosed verbatim interpolation swallowed the rest (B10)
            prev = "str"; i = j
            continue
        if cfg.get("verbatim") and text.startswith('@"', i):
            j, closed = _string_end(text, i + 1, n, '"', "double", True)
            if not closed:
                scan.uncertain = True   # a verbatim string with no closing quote swallowed the rest (B10)
            emit(text[i:j]); prev = "str"; i = j
            continue
        if cfg.get("rust_raw") and re.match(r'b?r#*"', text[i:i + 12]) and not (i and (text[i - 1].isalnum() or text[i - 1] == "_")):
            mm = re.match(r'b?r(#*)"', text[i:])
            close = '"' + mm.group(1)
            k = text.find(close, i + mm.end())
            if k < 0:
                scan.uncertain = True   # a raw string with no closer swallowed the rest (B10)
                j = n
            else:
                j = k + len(close)
            emit(text[i:j]); prev = "str"; i = j
            continue
        if cfg.get("herestring") and text.startswith(("@'", '@"'), i) and text[i + 2:i + 3] in ("\n", "\r"):
            close = "\n" + text[i + 1] + "@"
            k = text.find(close, i)
            if k < 0:
                scan.uncertain = True   # a here-string with no terminator swallowed the rest (B10)
                j = n
            else:
                j = k + len(close)
            emit(text[i:j]); prev = "str"; i = j
            continue
        if cfg.get("raw_backtick") and c == "`":
            k = text.find("`", i + 1)
            if k < 0:
                scan.uncertain = True   # a backtick string with no closer swallowed the rest (B10)
                j = n
            else:
                j = k + 1
            emit(text[i:j]); prev = "str"; i = j
            continue
        if cfg.get("template") and c == "`":
            j = i + 1
            seg = i
            closed = False
            while j < n:
                if text[j] == "\\":
                    j += 2
                    continue
                if text[j] == "`":
                    j += 1
                    closed = True
                    break
                if text.startswith("${", j):
                    scan.tok(text[seg:j + 2])
                    j = _scan_clike(text, cfg, scan, j + 2, n, brace_stop=True)
                    seg = j
                    j += 1
                    continue
                j += 1
            if not closed:
                scan.uncertain = True   # a template literal with no closer swallowed the rest (B10)
            scan.tok(text[seg:j]); prev = "str"; i = j
            continue
        if cfg.get("dollar") and c == "$" and not (i and (text[i - 1].isalnum() or text[i - 1] == "_")):
            mm = re.match(r"\$(\w*)\$", text[i:i + 66])
            if mm:
                close = mm.group(0)
                k = text.find(close, i + len(close))
                if k < 0:
                    scan.uncertain = True   # a dollar-quoted string with no closer swallowed the rest (B10)
                    j = n
                else:
                    j = k + len(close)
                emit(text[i:j]); prev = "str"; i = j
                continue
        if cfg.get("brackets") and c == "[":
            j = text.find("]", i)
            if j > 0 and "\n" not in text[i:j]:
                emit(text[i:j + 1]); prev = "str"; i = j + 1
                continue
        if cfg.get("chars") and c == "'":
            mm = _CHAR_LIT.match(text, i)
            if mm:
                emit(mm.group(0)); prev = "str"; i = mm.end()
            else:
                emit("'"); prev = "'"; i += 1
            continue
        if c in quotes:
            end, closed = _string_end(text, i, n, c, quotes[c], cfg.get("multiline_strings"))
            if cfg.get("bs_uncertain") and "\\" in text[i:end]:
                scan.uncertain = True   # MySQL backslash escapes: dialect-dependent (B6)
            if not closed and end >= n:
                scan.uncertain = True   # a string that runs to the end with no closing quote (B10)
            if cfg.get("dollar_hole") and c == '"' and "$" in text[i + 1:text.find('"', i + 1) + 1 or n]:
                j, closed = _scan_interp(text, i, n, cfg, scan, '"', "dollar")
                if not closed and j >= n:
                    scan.uncertain = True   # a template that runs to the end with no closing quote (B10)
            elif cfg.get("paren_interp") and c == '"':
                j, closed = _scan_interp(text, i, n, cfg, scan, '"', "paren")
                if not closed and j >= n:
                    scan.uncertain = True   # a string that runs to the end with no closing quote (B10)
            else:
                j = end
            emit(text[i:j]); prev = "str"; i = j
            continue
        if cfg.get("css_url") and text[i:i + 4].lower() == "url(":
            k = text.find(")", i)
            if k < 0:
                scan.uncertain = True   # an unquoted url( with no closer swallowed the rest (B10)
                j = n
            else:
                j = k + 1
            emit(text[i:j]); prev = "str"; i = j
            continue
        if cfg.get("regex") and c == "/" and prev in _REGEX_PREV:
            j, in_class, ok = i + 1, False, False
            while j < n:
                ch = text[j]
                if ch == "\\":
                    j += 2
                    continue
                if ch == "\n":
                    break
                if in_class:
                    if ch == "]":
                        in_class = False
                elif ch == "[":
                    in_class = True
                elif ch == "/":
                    ok = True
                    break
                j += 1
            if ok:
                j += 1
                while j < n and text[j].isalpha():
                    j += 1
                emit(text[i:j]); prev = "str"; i = j
                continue
        if c == "/" and prev == ")":
            scan.uncertain = True   # regex or division after ')': undecidable here (B10)
        if cfg.get("jsx") and c == "<" and prev in _JSX_PREV and re.match(r"</?[A-Za-z]", text[i:i + 2]):
            j = _tag_end(text, i, n)
            emit(text[i:j])
            if not text[i:j].endswith("/>"):
                k = _scan_jsx_children(text, cfg, scan, j, n)
                j2 = _tag_end(text, k, n)
                scan.tok(text[k:j2])
                i = j2
            else:
                i = j
            prev = "jsx"
            continue
        if c == "\n":
            scan.tok("\n"); sep = False; i += 1
            continue
        if c.isspace():
            sep = True
            while i < n and text[i].isspace() and text[i] != "\n":
                i += 1
            continue
        mm = _IDENT.match(text, i)
        if mm:
            word = mm.group(0)
            if cfg.get("cpp_raw") and word in ("R", "u8R", "uR", "UR", "LR") and text[mm.end():mm.end() + 1] == '"':
                rm = re.match(r'"([^(\s]{0,16})\(', text[mm.end():mm.end() + 20])
                if rm:
                    close = ")" + rm.group(1) + '"'
                    k = text.find(close, mm.end())
                    if k < 0:
                        scan.uncertain = True   # a raw string with no closer swallowed the rest (B10)
                        j = n
                    else:
                        j = k + len(close)
                    emit(text[i:j]); prev = "str"; i = j
                    continue
            emit(word); prev = word; i = mm.end()
            continue
        mm = _NUMBER.match(text, i)
        if mm:
            emit(mm.group(0)); prev = "num"; i = mm.end()
            continue
        emit(c); prev = c; i += 1
    return i


def _plain_tokens(text, scan):
    _scan_clike(text, _CLIKE["plain"], scan)


def _scan_shell(text, scan):
    n = len(text)
    i = 0
    pending = []   # heredoc delimiters opened on the current line
    while i < n:
        c = text[i]
        if c == "\n":
            scan.tok("\n")
            i += 1
            for delim, strip_tabs in pending:
                start = i
                closed = False
                while i < n:
                    e = text.find("\n", i)
                    e = n if e < 0 else e
                    line = text[i:e]
                    i = min(e + 1, n)
                    if (line.lstrip("\t") if strip_tabs else line).rstrip("\r") == delim:
                        closed = True
                        break
                if not closed:
                    scan.uncertain = True   # a heredoc with no terminator swallowed the rest (B10)
                scan.tok(text[start:i].rstrip("\r\n"))
                scan.tok("\n")
            pending = []
            continue
        if c == "#" and (i == 0 or text[i - 1] in " \t\n;&|()"):
            j = text.find("\n", i)
            j = n if j < 0 else j
            k = j - 1 if text[j - 1] == "\r" else j
            scan.comments.append((i, k, text[i + 1:k]))
            i = j
            continue
        if c == "\\":
            scan.tok(text[i:i + 2]); i += 2
            continue
        if text.startswith("<<", i) and not text.startswith("<<<", i):
            mm = re.match(r"<<(-?)\s*(['\"]?)([\w.-]+)\2", text[i:])
            if mm:
                pending.append((mm.group(3), bool(mm.group(1))))
                scan.tok(mm.group(0)); i += mm.end()
                continue
        if text.startswith("$'", i):
            j, closed = _string_end(text, i + 1, n, "'", "bs", True)
            if not closed:
                scan.uncertain = True   # a string with no closing quote swallowed the rest (B10)
            scan.tok(text[i:j]); i = j
            continue
        if c in "'\"`":
            j, closed = _string_end(text, i, n, c, None if c == "'" else "bs", True)
            if not closed:
                scan.uncertain = True   # a string with no closing quote swallowed the rest (B10)
            scan.tok(text[i:j]); i = j
            continue
        if c.isspace():
            i += 1
            continue
        mm = _IDENT.match(text, i) or _NUMBER.match(text, i)
        if mm:
            scan.tok(mm.group(0)); i = mm.end()
            continue
        scan.tok(c); i += 1


def _scan_hash(text, scan, perl=False):
    """`#` family (Ruby, R, Perl, YAML, TOML, Make, CMake, Terraform…): `#` starts a comment at
    line start or after whitespace, outside quotes. Triple-quoted strings, heredocs, Nix
    multiline strings, YAML quoted-and-continued scalars and block scalars are handled;
    anything subtler is why this lexer is not CERTAIN (B11)."""
    lines = text.split("\n")
    offs = [0]
    for ln in lines:
        offs.append(offs[-1] + len(ln) + 1)
    idx = 0
    scalar_indent = None
    in_triple = None
    in_quote = None      # a quoted scalar continued onto the next YAML line
    heredoc = None       # (terminator,) for <<EOF / <<~EOF / <<"EOF"
    in_nix = False
    while idx < len(lines):
        line = lines[idx]
        off = offs[idx]
        stripped = line.lstrip()
        ind = len(line) - len(stripped)
        if scalar_indent is not None:
            if stripped and ind <= scalar_indent:
                scalar_indent = None
            else:
                scan.tok(line); scan.tok("\n"); idx += 1
                continue
        if heredoc is not None:
            if stripped.rstrip("!;,").rstrip() == heredoc[0]:
                heredoc = None
            scan.tok(line); scan.tok("\n"); idx += 1
            continue
        if in_nix:
            if stripped.startswith("''"):
                in_nix = False
            scan.tok(line); scan.tok("\n"); idx += 1
            continue
        if in_quote is not None:
            if in_quote in line:
                in_quote = None
            scan.tok(line); scan.tok("\n"); idx += 1
            continue
        if in_triple is None and re.match(r"=begin\b", line):
            end = idx + 1
            while end < len(lines) and not re.match(r"=end\b", lines[end]):
                end += 1
            end = min(end, len(lines) - 1)
            scan.comments.append((off, offs[end] + len(lines[end]), "\n".join(lines[idx + 1:end])))
            scan.tok("\n")
            idx = end + 1
            continue
        k = 0
        if in_triple:
            e = line.find(in_triple)
            if e < 0:
                scan.tok(line); scan.tok("\n"); idx += 1
                continue
            scan.tok(line[:e + 3])
            k = e + 3
            in_triple = None
        code_start = k
        q = None
        cpos = None
        while k < len(line):
            ch = line[k]
            if q:
                if ch == "\\" and q != "'":
                    k += 2
                    continue
                if ch == q:
                    q = None
                k += 1
                continue
            if line.startswith(('"""', "'''"), k):
                e = line.find(line[k:k + 3], k + 3)
                if e < 0:
                    in_triple = line[k:k + 3]
                    k = len(line)
                    break
                k = e + 3
                continue
            if ch in "\"'":
                q = ch
            elif ch == "#" and (k == 0 or line[k - 1] in " \t") and not line.startswith("#{", k):
                cpos = k
                break
            k += 1
        code = line[code_start:cpos if cpos is not None else len(line)]
        if q is not None:
            in_quote = q       # the quote never closed: the scalar continues on the next line
        if cpos is not None:
            end = len(line) - 1 if line.endswith("\r") else len(line)
            scan.comments.append((off + cpos, off + end, line[cpos + 1:end]))
        _plain_tokens(code, scan)
        scan.tok("\n")
        # the delimiter follows `<<` immediately, as Ruby requires; Perl also allows whitespace
        # before a quoted one, which elsewhere is a shift of a string (`x << "s"`)
        hm = re.search(r"<<[~-]?(['\"]?)([A-Za-z_]\w*)\1", code)
        if hm is None and perl:
            hm = re.search(r"<<~?\s*(['\"])(\w+)\1", code)
        if hm and not code.rstrip().endswith(","):
            heredoc = (hm.group(2),)
        elif not perl and re.search(r"<<[~-]?\s+(['\"])\w+\1", code):
            scan.uncertain = True   # a shift of a string or a spaced quoted heredoc: undecidable here (B10)
        if code.rstrip().endswith("''") and not code.rstrip().endswith("''''"):
            in_nix = True
        if re.search(r"[|>][-+0-9]*\s*$", code):
            scalar_indent = ind
        idx += 1
    if heredoc is not None or in_triple is not None or in_nix or in_quote is not None:
        scan.uncertain = True   # a literal opened and never closed: the lines after it are inside it (B10)


def _scan_lines(text, scan, markers, ci=False, heredoc=False, continues=False):
    """Comments only at line start (after whitespace): Dockerfile, ignore files, INI, batch.
    Each code line is one verbatim token (whitespace inside it is content, B1); a heredoc
    opened with <<EOF (Dockerfile) and a value continued with a trailing backslash
    (.properties) are opaque, never comments (B5)."""
    off = 0
    pending = None   # heredoc terminator
    cont = False     # inside a backslash continuation
    for line in text.split("\n"):
        end = len(line) - 1 if line.endswith("\r") else len(line)
        if pending is not None:
            if line.rstrip("\r") == pending or line.strip() == pending:
                scan.tok(line[:end])
                scan.tok("\n")
                pending = None
            else:
                scan.tok(line[:end] if line.strip() else "")
                scan.tok("\n")
            off += len(line) + 1
            continue
        s = line.lstrip()
        k = len(line) - len(s)
        probe = s.lower() if ci else s
        hit = None if cont else next(
            (m for m in markers if probe.startswith(m)
             and (not m.isalpha() and not m.endswith("rem") or len(s) == len(m) or s[len(m)].isspace())), None)
        if hit:
            scan.comments.append((off + k, off + end, line[k + len(hit):end]))
        else:
            scan.tok(line[:end].rstrip() if line.strip() else "")
            if heredoc:
                m = re.search(r"<<-?\s*(['\"]?)([A-Za-z][\w.-]*)\1", line)
                if m:
                    pending = m.group(2)
            elif continues and line.rstrip().endswith("\\") and not line.rstrip().endswith("\\\\"):
                cont = True
            elif continues:
                cont = False
        scan.tok("\n")
        off += len(line) + 1
    if pending is not None:
        scan.uncertain = True   # a heredoc with no terminator swallowed the rest of the file (B10)


def _scan_fortran_fixed(text, scan):
    off = 0
    for line in text.split("\n"):
        if len(line) > 5 and line[5] in "!*" and line[:5].isspace():
            pass   # a continuation character in column 6, not a comment (B5)
        elif line[:1] in ("C", "c", "*", "!"):
            scan.comments.append((off, off + len(line.rstrip("\r")), line[1:]))
        else:
            sub = Scan()
            _scan_clike(line, _CLIKE["fortran"], sub)
            scan.comments.extend((a + off, b + off, t) for a, b, t in sub.comments)
            scan.tokens.extend(sub.tokens)
        scan.tok("\n")
        off += len(line) + 1


_JS_TYPE = re.compile(r"type\s*=\s*[\"']?([\w/+.-]+)", re.I)
_JS_TYPES = ("javascript", "module", "ecmascript", "jsx", "importmap")
_TAG = re.compile(r"<(script|style|textarea|title)[\s/>]", re.I)


def _scan_region(text, scan, i, close, lang_cfg):
    """Scan an embedded region, splitting out server code (`<?php … ?>`, `<% … %>`) so its
    comments are code-region comments, never template text (B8)."""
    j = i
    while j < close:
        k = min((x for x in (text.find("<?", j), text.find("<%", j)) if x >= 0), default=-1)
        if k < 0 or k >= close:
            _scan_clike(text, lang_cfg, scan, j, close)
            return
        _scan_clike(text, lang_cfg, scan, j, k)
        stop = "?>" if text.startswith("<?", k) else "%>"
        e = text.find(stop, k)
        e = close if e < 0 else e + len(stop)
        scan.tok(text[k:e])
        j = e


def _scan_markup(text, scan, embed=True, php=False, razor=False, aspnet=False):
    n = len(text)
    low = text.lower()
    i = 0
    while i < n:
        if php and text.startswith("<?", i) and not text.startswith("<?xml", i):
            k = i + (5 if text.startswith("<?php", i) else 3 if text.startswith("<?=", i) else 2)
            scan.tok(text[i:k])
            j = _scan_clike(text, _CLIKE["php"], scan, k, n, stop="?>")
            if j < n:
                scan.tok("?>")
                j += 2
            i = j
            continue
        if razor and text.startswith("@@", i):
            scan.tok("@@"); i += 2
            continue
        if razor and text.startswith("@*", i):
            j = text.find("*@", i + 2)
            if j < 0:
                scan.uncertain = True
                scan.tok(text[i:]); return
            scan.comments.append((i, j + 2, text[i + 2:j]))
            i = j + 2
            continue
        if razor and text.startswith("@{", i):
            scan.tok("@{")
            j = _scan_clike(text, _CLIKE["csharp"], scan, i + 2, n, brace_stop=True)
            scan.tok("}")
            i = j + 1
            continue
        if aspnet and text.startswith("<%--", i):
            j = text.find("--%>", i + 4)
            if j < 0:
                scan.uncertain = True
                scan.tok(text[i:]); return
            scan.comments.append((i, j + 4, text[i + 4:j]))
            i = j + 4
            continue
        if aspnet and text.startswith("<%", i):
            j = text.find("%>", i + 2)
            j = n if j < 0 else j + 2
            scan.tok(text[i:j]); i = j
            continue
        if text.startswith("<!--", i):
            j = text.find("-->", i + 4)
            if j < 0:
                scan.uncertain = True   # unterminated: never a unit (B10)
                scan.tok(text[i:]); return
            scan.comments.append((i, j + 3, text[i + 4:j]))
            i = j + 3
            continue
        if text.startswith("<![CDATA[", i):
            k = text.find("]]>", i)
            if k < 0:
                scan.uncertain = True   # a CDATA section with no closer swallowed the rest (B10)
                j = n
            else:
                j = k + 3
            scan.tok(text[i:j]); i = j
            continue
        if embed and _TAG.match(low, i):
            tag = _TAG.match(low, i).group(1)
            gt = text.find(">", i)
            if gt < 0:
                scan.tok(text[i:])
                return
            head = low[i:gt + 1]
            scan.tok(text[i:gt + 1])
            close = low.find("</" + tag, gt + 1)
            close = n if close < 0 else close
            if tag in ("textarea", "title"):
                scan.tok(text[gt + 1:close])   # RCDATA: text, never comments (B8)
            elif tag == "script":
                m = _JS_TYPE.search(head)
                ty = m.group(1).lower() if m else ""
                if ty and not any(ty == t or ty.endswith("." + t) for t in _JS_TYPES):
                    scan.tok(text[gt + 1:close])   # a template, not JavaScript: opaque (B8)
                else:
                    _scan_region(text, scan, gt + 1, close, _CLIKE["js"])
            else:
                lm = re.search(r"lang\s*=\s*[\"']?([\w-]+)", head)
                lang = (lm.group(1).lower() if lm else "css")
                _scan_region(text, scan, gt + 1, close, _CLIKE.get(lang, _CLIKE["css"]))
            i = close
            continue
        if text.startswith("<", i):
            j = _tag_end(text, i, n)
            for t in re.findall(r"\"[^\"]*\"|'[^']*'|[\w:.-]+|\S", text[i:j]):
                scan.tok(t)
            i = j
            continue
        j = text.find("<", i)
        j = n if j < 0 else j
        for mm in re.finditer(r"\S+|\s+", text[i:j]):
            g = mm.group(0)
            if g[0].isspace():
                scan.tok("\n" if "\n" in g else " ")   # B1: text spacing is content in markup
            else:
                scan.tok(g)
        i = j


def _scan_python(text, scan, fine):
    toks = list(tokenize.generate_tokens(io.StringIO(text).readline))
    starts = [0]
    for ln in text.split("\n"):
        starts.append(starts[-1] + len(ln) + 1)

    def off(rc):
        return starts[rc[0] - 1] + rc[1]

    doc = set()
    if fine:
        tree = ast.parse(text)
        for node in ast.walk(tree):
            if isinstance(node, (ast.Module, ast.ClassDef, ast.FunctionDef, ast.AsyncFunctionDef)) and node.body:
                first = node.body[0]
                if (isinstance(first, ast.Expr) and isinstance(first.value, ast.Constant)
                        and isinstance(first.value.value, str)):
                    doc.add((first.lineno, first.col_offset))
    pending = False     # whitespace or a comment ran before the next token on this line (B1)
    last_row = None
    skip_newline = False
    for t in toks:
        if t.type == tokenize.COMMENT:
            scan.comments.append((off(t.start), off(t.end), t.string[1:]))
            pending = True
            continue
        if t.type == tokenize.STRING and t.start in doc:
            scan.comments.append((off(t.start), off(t.end), "\x00docstring\n" + t.string))
            pending = True
            skip_newline = True
            continue
        if t.type in (tokenize.NL, tokenize.ENCODING, tokenize.ENDMARKER):
            pending = False
            continue
        if t.type == tokenize.NEWLINE:
            if not skip_newline:
                scan.tok("\n")
            skip_newline = False
            pending = False
            last_row = None
        elif t.type in (tokenize.INDENT, tokenize.DEDENT):
            scan.tok(tokenize.tok_name[t.type])
        else:
            skip_newline = False
            if pending and t.start[0] == last_row and scan.tokens:
                scan.tok(" ")
            scan.tok(t.string)
            pending = False
            last_row = t.end[0]
    if doc:
        scan.doc = True   # a docstring is a runtime value (__doc__, doctest): the suite decides
    return bool(doc)


# A Java unicode escape of a character that ends or opens a comment, string or char literal:
# javac decodes it in phase 1, so `// done \u000a deleteDatabase();` is a comment and live code.
# Over-matching (an even backslash run, an escape inside a string) only costs certainty.
_JAVA_UESC = re.compile(r"\\+u+(000[aAdD]|002[2aAfF]|0027|005[cC])")


def scan(text, path, fine=False):
    """Lex one file. Returns (lang, Scan, certain). Raises UnsupportedLanguage."""
    lang = language_for(path)
    if lang is None:
        raise UnsupportedLanguage(f"{path}: no comment syntax is known for this file type")
    s = Scan()
    certain = lang in CERTAIN
    try:
        if lang == "python":
            _scan_python(text, s, fine)   # docstrings set s.doc
        elif lang == "razor":
            _scan_markup(text, s, embed=True, razor=True)
        elif lang == "aspnet":
            _scan_markup(text, s, embed=True, aspnet=True)
        elif lang in ("html", "xml"):
            _scan_markup(text, s, embed=(lang == "html"))
        elif lang == "php":
            _scan_markup(text, s, embed=True, php=True)
        elif lang == "shell":
            _scan_shell(text, s)
        elif lang == "hash":
            _scan_hash(text, s, perl=PurePosixPath(str(path).replace("\\", "/")).suffix.lower() in (".pl", ".pm"))
        elif lang == "hashline":
            _scan_lines(text, s, ("#",), heredoc=True)
        elif lang == "ini":
            _scan_lines(text, s, ("#", ";"))
        elif lang == "properties":
            _scan_lines(text, s, ("#", "!"), continues=True)
        elif lang == "batch":
            _scan_lines(text, s, ("@rem", "rem", "::"), ci=True)
        elif lang == "fortran-fixed":
            _scan_fortran_fixed(text, s)
        elif lang == "none":
            _scan_clike(text, {"quotes": {'"': "bs"}}, s)
        else:
            _scan_clike(text, _CLIKE[lang], s)
    except (UnicodeError, RecursionError, ValueError, MemoryError, tokenize.TokenError, SyntaxError):
        # D5: a file the primary scanner cannot read falls back to a conservative line scan,
        # never a crash, and its certainty is gone
        s = Scan()
        s.uncertain = True
        try:
            _scan_hash(text, s)
        except Exception:
            pass
    if lang == "java" and _JAVA_UESC.search(text):
        s.uncertain = True   # javac decodes \uXXXX before lexing; this scanner does not (R-lexer 2)
    if s.uncertain or s.doc:
        certain = False
    return lang, s, certain


def code_tokens(text, path, fine=False):
    """Non-comment tokens with runs of newlines collapsed. Returns (tokens, certain)."""
    # A leading BOM is an encoding signature, never a token: removing a BOM'd line-1 comment
    # must not glue it to the first code token (R-gates 4). Replay still compares bytes.
    if text.startswith("﻿"):
        text = text[1:]
    _, s, certain = scan(text, path, fine)
    out = []
    for t in s.tokens:
        if t == "\n" and (not out or out[-1] == "\n"):
            continue
        out.append(t)
    while out and out[-1] == "\n":
        out.pop()
    return out, certain


# ------------------------------------------------------------------ comment units
class Unit:
    """A classifiable comment unit. Lines 1-indexed inclusive; columns 0-indexed, end exclusive.
    `whole`: every line of the span holds nothing but comment, so removing the unit removes
    its lines."""
    __slots__ = ("sl", "sc", "el", "ec", "whole", "kind")

    def __init__(self, sl, sc, el, ec, whole, kind="comment"):
        self.sl, self.sc, self.el, self.ec, self.whole, self.kind = sl, sc, el, ec, whole, kind

    def span(self):
        return f"{self.sl}:{self.sc}-{self.el}:{self.ec}"

    def __repr__(self):
        return f"Unit({self.span()}, whole={self.whole}, {self.kind})"


def comment_units(text, path, fine=False, is_directive=None):
    """Classifiable comment units of one file, in file order.

    `comment` rule (fine=False): whole-line comments on consecutive lines form one unit; a
    comment sharing a line with code is no unit and stays untouched.
    `comment-fine` rule: each trailing comment, and each Python docstring, is also a unit of
    its own. A comment with code on both sides of it is never a unit, not even under
    `comment-fine` (B1). A tool directive is never a unit and splits its group; a group
    holding a license marker is excluded whole, and a license marker anywhere in the comment
    header before the first code line protects every header group (C2)."""
    is_directive = is_directive or directive_matcher()
    lang, s, _ = scan(text, path, fine)
    if lang == "none":
        return []
    lines = text.split("\n")
    starts = [0]
    for ln in lines:
        starts.append(starts[-1] + len(ln) + 1)
    bom = text.startswith("﻿")

    def rc(o):
        r = bisect.bisect_right(starts, o) - 1
        return r + 1, o - starts[r]

    def before(sl, sc):
        ln = lines[sl - 1]
        if sl == 1 and bom:
            return ln[1:][:max(sc - 1, 0)].strip()
        return ln[:sc].strip()

    def after(el, ec):
        return lines[el - 1][ec:].rstrip("\r").strip()

    # C2: does any comment before the first code line carry a license marker?
    spans = sorted((a, min(b, len(text))) for a, b, _ in s.comments)
    blanks = " \t\r\f\v﻿"

    def line_has_code(i):
        lo, hi = starts[i], starts[i] + len(lines[i])
        pos, k = lo, 0
        while k < len(spans) and spans[k][1] <= lo:
            k += 1
        for a, b in spans[k:]:
            if a >= hi:
                break
            if pos < a and any(ch not in blanks for ch in text[pos:a]):
                return True
            pos = max(pos, b)
        return pos < hi and any(ch not in blanks for ch in text[pos:hi])

    first_code = next((i for i in range(len(lines)) if line_has_code(i)), None)
    header_end = starts[first_code] if first_code is not None else len(text)
    header_licence = any(a < header_end and is_directive(inner) == "license"
                         for a, b, inner in s.comments)

    items = []   # (Unit, flag)
    for a, b, inner in sorted(s.comments):
        while b > a and text[b - 1] in "\r\n":
            b -= 1
        sl, sc = rc(a)
        el, ec = rc(b)
        left, right = before(sl, sc), after(el, ec)
        whole = left == "" and right == ""
        if left and right:
            continue   # code on both sides: never a unit, not even under comment-fine (B1)
        kind = "comment"
        if inner.startswith("\x00docstring\n"):
            kind, inner = "docstring", inner[len("\x00docstring\n"):].strip().strip("\"'")
        elif inner.startswith("\x00doc\n"):
            kind, inner = "doc", inner[len("\x00doc\n"):]
        if kind in ("docstring", "doc"):
            if is_directive(inner) == "license":
                continue   # a license docstring or doc comment is a notice, not a unit (C2/C4)
            items.append((Unit(sl, sc, el, ec, whole, kind), None))
            continue
        if a == (1 if bom else 0) and text[1 if bom else 0:].startswith("#!"):
            continue   # shebang: an executable directive
        if lang == "python" and sl <= 2 and re.match(r"^[ \t\f]*#.*?coding[:=]", lines[sl - 1]):
            continue   # PEP 263 encoding cookie
        flag = is_directive(inner)
        if flag is None and lang == "java" and _JAVA_UESC.search(inner):
            flag = "escape"   # javac ends or reshapes this comment: never a unit (R-lexer 2)
        if flag is None and lang in ("js", "css", "scss", "sass") and inner.startswith("!"):
            flag = "license"   # /*! … */ is a preserved banner
        if flag is None and header_licence and b <= header_end:
            flag = "license"   # part of a header that carries a licence notice (C2)
        items.append((Unit(sl, sc, el, ec, whole), flag))

    units = []
    group = []

    def flush():
        if group and not any(f == "license" for _, f in group):
            run = None
            for u, f in group:
                if f:
                    if run:
                        units.append(run)
                    run = None
                elif run and u.sl == run.el + 1:
                    run = Unit(run.sl, run.sc, u.el, u.ec, True)
                else:
                    if run:
                        units.append(run)
                    run = Unit(u.sl, u.sc, u.el, u.ec, True)
            if run:
                units.append(run)
        group.clear()

    for u, f in items:
        if not u.whole or u.kind in ("docstring", "doc"):
            flush()
            if fine and not f:
                units.append(u)
            continue
        if group and u.sl != group[-1][0].el + 1:
            flush()
        group.append((u, f))
    flush()
    return units
